# Generated by Django 3.2.1 on 2021-05-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_size', models.FloatField()),
                ('image_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=500)),
                ('is_admin', models.IntegerField()),
                ('user_join_date', models.DateTimeField(verbose_name='Date Joined')),
            ],
        ),
    ]
