# Generated by Django 3.2.1 on 2021-05-07 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='caption',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='media/images')),
                ('image', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.images')),
            ],
        ),
    ]
