# Generated by Django 3.2.1 on 2021-05-08 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210507_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='title',
        ),
    ]
