# Generated by Django 3.2.1 on 2021-05-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_images_images_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='title',
        ),
        migrations.AddField(
            model_name='images',
            name='images',
            field=models.ImageField(default='null', upload_to='.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.FileField(upload_to='.'),
        ),
    ]
