# Generated by Django 3.2.1 on 2021-05-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210508_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='current_user',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
